### ISSUE TITLE
Inconsistent UCPD CFG register names

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/cmsis_device_u5#1]
`UCPD_TypeDef` struct defined in  [stm32u575xx.h](https://github.com/STMicroelectronics/cmsis_device_u5/blob/06d7edade7167b0eafdd550bf77cfc4fa98eae2e/Include/stm32u575xx.h#L1245) contains **CFG1-CFG3** registers while in STM32U5 reference manual [RM0456](https://www.st.com/resource/en/reference_manual/rm0456-stm32u5-series-armbased-32bit-mcus-stmicroelectronics.pdf) in sections 74.8.1-74.8.3 those registers are named **CFGR1-CFGR3**.

Another inconsistency: RM0456 section 74.8.1 defines **CFGR1**.PSC_**USBPD**CLK register value, but HAL implements **CFG1**.UCPD_CFG1_PSC_**UCPD***CLK (USBPDCLK vs UCPDCLK).

This can be confusing.
Please fix code or RM docs - preferably RM, since naming used in HAL makes more sense

**Comment by tdjastrzebski** [comment]
The same applies to STM32H5xx, see
[STM32U5xx UCPD RM0456 documentation inconsistency](https://community.st.com/t5/stm32-mcu-products/stm32u5xx-ucpd-rm0456-documentation-inconsistency/m-p/584411#M221422)

**Comment by ALABSTM** [comment]
ST Internal Reference: 167493

**Comment by ALABSTM** [comment]
Hi @tdjastrzebski,

Our development team acknowledged your request. However, they made the choice **not** to deploy such an update for the moment as it would impact the firmware as a whole.

Hence, please allow me to close this issue. Thank you for your comprehension and thank you again for having reported.

With regards,
