### ISSUE TITLE
Wrong VREFBUF voltage scale #define

### ISSUE THREAD

**Issue by adel-kah** [STMicroelectronics/cmsis_device_u5#2]
In the stm32u5xxxx.h files, the following #define does not setup correctly the VREFBUF voltage scale :
`#define LL_VREFBUF_VOLTAGE_SCALE3          VREFBUF_CSR_VRS_2       /*!< Voltage reference scale 1 (VREF_OUT4) */`

VREFBUF_CSR_VRS_2 should be (0x03UL<< VREFBUF_CSR_VRS_Pos) :
`#define VREFBUF_CSR_VRS_2       (0x04UL<< VREFBUF_CSR_VRS_Pos)                      /*!< 0x00000030 */`

**Comment by TOUNSTM** [comment]
ST Internal Reference: 172777

**Comment by RJMSTM** [comment]
Fixed in : 46d5877874a9fb5cd3ebd9044171b0c946d7716b
