### ISSUE TITLE
46d5877874a9fb reintroduces error corrected in 3abe881508869a9e

### ISSUE THREAD

**Issue by UweBonnes** [STMicroelectronics/cmsis_device_u5#3]
Head again misses the opening parenthesis.

Does nobody work with these headers?
 
#define USB_OTG_GCCFG_FSVMINUS_Pos               (2U)
-#define USB_OTG_GCCFG_FSVMINUS_Msk               (0x1U << USB_OTG_GCCFG_FSVMINUS_Pos)        /*!< 0x00000004 */
+#define USB_OTG_GCCFG_FSVMINUS_Msk               0x1U << USB_OTG_GCCFG_FSVMINUS_Pos)         /*!< 0x00000004 */

**Comment by ALABSTM** [comment]
Hi @UweBonnes,

Thank you for the heads-up. Indeed, this is an unwanted change. We'll have this fixed as soon as possible.

With regards,

**Comment by ALABSTM** [comment]
Fixed in commit 48a64b6a00d7627b6c98fcf565cc6cf2b714b659
